package com.pokelike.game

data class Evolution(val toId: String, val level: Int = 0, val stone: String? = null)

data class Species(
    val id: String,
    val dexNo: Int,
    val name: String,
    val types: List<Type>,
    val hp: Int, val atk: Int, val def: Int, val spa: Int, val spd: Int, val spe: Int,
    val catchRate: Int,
    val baseExp: Int,
    val sprite: String,
    val colorA: Int,
    val colorB: Int,
    val learnset: List<Pair<Int, String>>,
    val evolution: Evolution? = null,
    val dexText: String = ""
) {
    fun base(stat: Stat): Int = when (stat) {
        Stat.HP -> hp
        Stat.ATK -> atk
        Stat.DEF -> def
        Stat.SPA -> spa
        Stat.SPD -> spd
        else -> spe
    }
}

object Dex {

    private fun ls(vararg p: Pair<Int, String>) = p.toList()

    private val species: List<Species> = listOf(
        // ---------------------------- Starter: Feuer ----------------------------
        Species("flamki", 1, "Flamki", listOf(Type.FEUER),
            39, 52, 43, 60, 50, 65, 45, 62, "QUAD", 0xFFF06030.toInt(), 0xFFFFD070.toInt(),
            ls(1 to "kratzer", 1 to "heuler", 7 to "glut", 12 to "ruckzuck", 18 to "flammenrad",
                24 to "schlitzer", 30 to "feuerzahn", 38 to "flammenwurf", 46 to "feuersturm"),
            Evolution("flammor", 16),
            "Ein neugieriges Feuermonster. Die Flamme an seinem Schweif zeigt seine Laune."),
        Species("flammor", 2, "Flammor", listOf(Type.FEUER),
            58, 64, 58, 80, 65, 80, 45, 142, "QUAD", 0xFFE04020.toInt(), 0xFFFFB040.toInt(),
            ls(1 to "kratzer", 12 to "ruckzuck", 20 to "flammenrad", 27 to "feuerzahn",
                34 to "flammenwurf", 42 to "schlitzer", 50 to "feuersturm"),
            Evolution("infernox", 34),
            "Seine Flammen werden heisser, wenn es einen wuerdigen Gegner spuert."),
        Species("infernox", 3, "Infernox", listOf(Type.FEUER, Type.DRACHE),
            88, 104, 82, 118, 90, 100, 45, 240, "DRAGON", 0xFFD03018.toInt(), 0xFFFFC048.toInt(),
            ls(1 to "flammenwurf", 36 to "drachenklaue", 44 to "drachentanz", 52 to "feuersturm",
                60 to "drachenpuls", 68 to "hyperstrahl"),
            null,
            "Sein Bruellen laesst ganze Taeler erzittern. Legenden nennen es Sohn des Vulkans."),

        // ---------------------------- Starter: Wasser ----------------------------
        Species("aquino", 4, "Aquino", listOf(Type.WASSER),
            44, 48, 65, 50, 64, 43, 45, 63, "FISH", 0xFF4890E0.toInt(), 0xFFB0E0FF.toInt(),
            ls(1 to "tackle", 1 to "haertner", 7 to "aquaknarre", 13 to "nassschweif",
                19 to "blubbstrahl", 26 to "frostatem", 33 to "aquahaubitze", 40 to "surfer",
                48 to "hydropumpe"),
            Evolution("wavox", 16),
            "Sein Panzer haelt sogar Felsstuerze aus. Es liebt ruhige Buchten."),
        Species("wavox", 5, "Wavox", listOf(Type.WASSER),
            62, 64, 82, 66, 82, 58, 45, 142, "FISH", 0xFF2A70C8.toInt(), 0xFF90D0FF.toInt(),
            ls(1 to "aquaknarre", 19 to "blubbstrahl", 27 to "frostatem", 35 to "aquahaubitze",
                42 to "surfer", 50 to "eisstrahl", 56 to "hydropumpe"),
            Evolution("tidalon", 34),
            "Es spuert Stroemungen kilometerweit und findet so immer den Heimweg."),
        Species("tidalon", 6, "Tidalon", listOf(Type.WASSER, Type.EIS),
            90, 94, 110, 105, 106, 78, 45, 240, "DRAGON", 0xFF1E5CB4.toInt(), 0xFF9EE8F0.toInt(),
            ls(1 to "surfer", 36 to "eisstrahl", 44 to "panzerschutz", 52 to "hydropumpe",
                60 to "blizzard", 68 to "hyperstrahl"),
            null,
            "Der Herrscher der kalten Tiefsee. Sein Atem laesst Wellen gefrieren."),

        // ---------------------------- Starter: Pflanze ----------------------------
        Species("sproutz", 7, "Sproutz", listOf(Type.PFLANZE),
            45, 49, 49, 65, 65, 45, 45, 64, "PLANT", 0xFF58B848.toInt(), 0xFFC0E878.toInt(),
            ls(1 to "tackle", 1 to "heuler", 7 to "rankenhieb", 13 to "giftpuder",
                20 to "gigasauger", 27 to "wachstum", 34 to "kugelsaat", 41 to "schlafpuder",
                48 to "blattgeissel"),
            Evolution("blattor", 16),
            "Die Knospe auf seinem Ruecken speichert Sonnenlicht wie eine Batterie."),
        Species("blattor", 8, "Blattor", listOf(Type.PFLANZE),
            62, 64, 66, 82, 82, 60, 45, 142, "PLANT", 0xFF3F9E36.toInt(), 0xFFA8D860.toInt(),
            ls(1 to "rankenhieb", 20 to "gigasauger", 28 to "wachstum", 36 to "kugelsaat",
                44 to "schlafpuder", 52 to "blattgeissel", 58 to "solarstrahl"),
            Evolution("floravar", 34),
            "Wenn seine Bluete duftet, schlafen selbst wilde Monster friedlich ein."),
        Species("floravar", 9, "Floravar", listOf(Type.PFLANZE, Type.GIFT),
            98, 92, 96, 110, 108, 70, 45, 240, "PLANT", 0xFF2E8C2A.toInt(), 0xFFE070C0.toInt(),
            ls(1 to "kugelsaat", 36 to "toxin", 44 to "blattgeissel", 52 to "schlammbombe",
                60 to "solarstrahl", 68 to "hyperstrahl"),
            null,
            "Seine Riesenbluete verstroemt einen Duft, der Wunden heilen soll."),

        // ---------------------------- Normale Wildmonster ----------------------------
        Species("ratzel", 10, "Ratzel", listOf(Type.NORMAL),
            30, 56, 35, 25, 35, 72, 255, 51, "QUAD", 0xFF9C8058.toInt(), 0xFFE8D8B0.toInt(),
            ls(1 to "tackle", 4 to "heuler", 9 to "furienschlag", 14 to "ruckzuck",
                20 to "schlitzer", 27 to "bodycheck"),
            Evolution("rattmar", 18),
            "Frech und schnell. Es nagt sich durch alles, was ihm im Weg liegt."),
        Species("rattmar", 11, "Rattmar", listOf(Type.NORMAL),
            55, 81, 60, 50, 70, 97, 127, 145, "QUAD", 0xFF7A6242.toInt(), 0xFFD8C08C.toInt(),
            ls(1 to "furienschlag", 20 to "schlitzer", 27 to "bodycheck", 34 to "agilitaet",
                42 to "kreuzhieb", 50 to "hyperstrahl"),
            null,
            "Seine Schneidezaehne wachsen ein Leben lang und durchtrennen Stahlrohre."),
        Species("piepsi", 12, "Piepsi", listOf(Type.NORMAL),
            40, 45, 40, 35, 35, 56, 255, 50, "BIRD", 0xFFC0A870.toInt(), 0xFFF8F0D0.toInt(),
            ls(1 to "tackle", 5 to "sandwirbel", 11 to "ruckzuck", 17 to "furienschlag",
                23 to "schlitzer", 30 to "agilitaet"),
            Evolution("sturmfalk", 20),
            "Ein zutraulicher Vogel, der Reisenden gerne den Weg zeigt."),
        Species("sturmfalk", 13, "Sturmfalk", listOf(Type.NORMAL, Type.KAMPF),
            70, 90, 65, 55, 62, 101, 90, 159, "BIRD", 0xFF8C6A3A.toInt(), 0xFFF0E0B0.toInt(),
            ls(1 to "ruckzuck", 24 to "schlitzer", 31 to "karateschlag", 38 to "agilitaet",
                46 to "kreuzhieb", 54 to "bodycheck"),
            null,
            "Es stuerzt aus grosser Hoehe herab und trifft mit der Wucht eines Felsens."),
        Species("raupix", 14, "Raupix", listOf(Type.KAEFER),
            45, 30, 35, 20, 20, 45, 255, 39, "BUG", 0xFF88C040.toInt(), 0xFFE8F0A0.toInt(),
            ls(1 to "tackle", 1 to "fadenschuss", 6 to "kaeferbiss"),
            Evolution("kokonix", 7),
            "Kaut Tag und Nacht an Blaettern, um schnell zu wachsen."),
        Species("kokonix", 15, "Kokonix", listOf(Type.KAEFER),
            50, 25, 60, 25, 30, 30, 120, 72, "COCOON", 0xFF9AA84C.toInt(), 0xFFD8D888.toInt(),
            ls(1 to "haertner", 1 to "fadenschuss", 10 to "kaeferbiss"),
            Evolution("mothara", 10),
            "Bewegungslos, aber innen findet eine gewaltige Verwandlung statt."),
        Species("mothara", 16, "Mothara", listOf(Type.KAEFER, Type.GIFT),
            62, 48, 52, 92, 82, 78, 45, 178, "MOTH", 0xFF7A68C0.toInt(), 0xFFE8D0F8.toInt(),
            ls(1 to "silberhauch", 12 to "giftpuder", 18 to "schlafpuder", 25 to "kaefergebrumm",
                32 to "matschbombe", 40 to "konfustrahl", 48 to "schlammbombe"),
            null,
            "Der Staub seiner Fluegel schimmert giftig im Mondlicht."),
        Species("zappel", 17, "Zappel", listOf(Type.ELEKTRO),
            35, 45, 40, 62, 50, 85, 190, 62, "SPARK", 0xFFF0D030.toInt(), 0xFFFFF8B0.toInt(),
            ls(1 to "donnerschock", 6 to "heuler", 11 to "donnerwelle", 17 to "funkenflug",
                24 to "agilitaet", 32 to "donnerblitz"),
            Evolution("voltrax", 24),
            "Speichert Strom in den Backentaschen und knistert bei Aufregung."),
        Species("voltrax", 18, "Voltrax", listOf(Type.ELEKTRO),
            62, 72, 62, 98, 82, 112, 75, 172, "SPARK", 0xFFE8A818.toInt(), 0xFFFFE870.toInt(),
            ls(1 to "funkenflug", 26 to "agilitaet", 33 to "donnerblitz", 41 to "ladungsstoss",
                49 to "donner", 56 to "hyperstrahl"),
            null,
            "Ein einziger Sprung erzeugt genug Strom fuer eine ganze Stadt."),
        Species("steinkopf", 19, "Steinkopf", listOf(Type.GESTEIN),
            52, 72, 98, 25, 32, 25, 190, 68, "ROCK", 0xFF9A8858.toInt(), 0xFFCFC098.toInt(),
            ls(1 to "tackle", 1 to "haertner", 8 to "steinwurf", 15 to "panzerschutz",
                22 to "steinhagel", 30 to "felswurf", 38 to "erdbeben"),
            Evolution("felsberg", 26),
            "Sein Koerper besteht aus verdichtetem Gestein und wiegt eine halbe Tonne."),
        Species("felsberg", 20, "Felsberg", listOf(Type.GESTEIN, Type.KAMPF),
            82, 104, 130, 38, 48, 38, 60, 175, "ROCK", 0xFF7A6A40.toInt(), 0xFFB8A878.toInt(),
            ls(1 to "steinhagel", 28 to "karateschlag", 36 to "felswurf", 44 to "erdbeben",
                52 to "steinkante", 60 to "nahkampf"),
            null,
            "Es rollt Berghaenge hinab und bahnt sich stur seinen Weg durch Felswaende."),
        Species("giftling", 21, "Giftling", listOf(Type.GIFT),
            48, 52, 48, 58, 52, 52, 190, 66, "BLOB", 0xFF9C50A8.toInt(), 0xFFD8A0E0.toInt(),
            ls(1 to "tackle", 6 to "saeure", 12 to "giftstachel", 19 to "schwaechler",
                26 to "matschbombe", 34 to "toxin", 42 to "schlammbombe"),
            Evolution("toxarr", 24),
            "Es hinterlaesst eine Spur aus aetzendem Schleim."),
        Species("toxarr", 22, "Toxarr", listOf(Type.GIFT),
            75, 82, 72, 88, 78, 72, 75, 168, "BLOB", 0xFF7A3088.toInt(), 0xFFC080D8.toInt(),
            ls(1 to "matschbombe", 28 to "toxin", 36 to "schlammbombe", 44 to "saeure",
                52 to "erdbeben", 58 to "hyperstrahl"),
            null,
            "In seinem Inneren brodeln Gifte, die selbst Metall aufloesen."),
        Species("frostli", 23, "Frostli", listOf(Type.EIS),
            46, 42, 48, 68, 62, 58, 150, 72, "ICE", 0xFF88D8E8.toInt(), 0xFFF0FFFF.toInt(),
            ls(1 to "tackle", 7 to "frostatem", 13 to "haertner", 20 to "eishieb",
                28 to "frostschleier", 36 to "eisstrahl", 44 to "blizzard"),
            Evolution("glaciar", 30),
            "Wo es schlaeft, bildet sich ueber Nacht eine Schicht aus Raureif."),
        Species("glaciar", 24, "Glaciar", listOf(Type.EIS, Type.GESTEIN),
            78, 74, 92, 104, 96, 74, 60, 182, "ICE", 0xFF50A8D0.toInt(), 0xFFD0F8FF.toInt(),
            ls(1 to "eishieb", 32 to "eisstrahl", 40 to "steinkante", 48 to "frostschleier",
                56 to "blizzard", 62 to "hyperstrahl"),
            null,
            "Sein Kristallpanzer bricht das Licht in tausend Regenbogen."),
        Species("boxor", 25, "Boxor", listOf(Type.KAMPF),
            52, 74, 48, 26, 42, 58, 180, 70, "BIPED", 0xFFC06040.toInt(), 0xFFF0C0A0.toInt(),
            ls(1 to "tackle", 6 to "karateschlag", 13 to "heuler", 20 to "steigerungshieb",
                28 to "kraftkoloss", 36 to "kreuzhieb"),
            Evolution("kampfax", 28),
            "Es trainiert jeden Tag gegen Felsen, bis seine Faeuste rauchen."),
        Species("kampfax", 26, "Kampfax", listOf(Type.KAMPF, Type.GESTEIN),
            85, 118, 78, 38, 66, 78, 60, 180, "BIPED", 0xFF9A4028.toInt(), 0xFFE0A078.toInt(),
            ls(1 to "kraftkoloss", 30 to "steinhagel", 38 to "kreuzhieb", 46 to "erdbeben",
                54 to "nahkampf", 60 to "steinkante"),
            null,
            "Ein Schlag seiner Faust zertruemmert massive Felsbloecke."),
        Species("schemen", 27, "Schemen", listOf(Type.GEIST),
            42, 36, 36, 74, 58, 72, 170, 74, "GHOST", 0xFF6A58A0.toInt(), 0xFFB8A8E8.toInt(),
            ls(1 to "schattenstoss", 8 to "nachtnebel", 15 to "konfustrahl", 22 to "schattenklaue",
                30 to "fluch", 38 to "spukball"),
            Evolution("nachtgeist", 30),
            "Es lebt in alten Ruinen und kichert, wenn Reisende sich verirren."),
        Species("nachtgeist", 28, "Nachtgeist", listOf(Type.GEIST, Type.GIFT),
            64, 58, 54, 112, 82, 104, 55, 186, "GHOST", 0xFF4A3878.toInt(), 0xFF9880D0.toInt(),
            ls(1 to "schattenklaue", 32 to "spukball", 40 to "toxin", 48 to "konfustrahl",
                56 to "schlammbombe", 62 to "hyperstrahl"),
            null,
            "Wer ihm in die Augen sieht, traeumt drei Naechte lang wirres Zeug."),
        Species("drakling", 29, "Drakling", listOf(Type.DRACHE),
            46, 58, 48, 52, 52, 52, 45, 70, "DRAGON", 0xFF6A70D8.toInt(), 0xFFC0C8FF.toInt(),
            ls(1 to "tackle", 8 to "drachenwut", 16 to "haertner", 24 to "drachenklaue",
                32 to "drachentanz", 40 to "drachenpuls", 48 to "wutanfall"),
            Evolution("draconar", 32),
            "Ein junger Drache, der noch ueben muss, um fliegen zu koennen."),
        Species("draconar", 30, "Draconar", listOf(Type.DRACHE),
            66, 82, 72, 68, 72, 68, 45, 148, "DRAGON", 0xFF4A50C0.toInt(), 0xFFA8B0F8.toInt(),
            ls(1 to "drachenklaue", 34 to "drachentanz", 42 to "drachenpuls", 50 to "eisstrahl",
                58 to "wutanfall"),
            Evolution("draconis", 48),
            "Um seinen Hals wachsen Kristalle, die im Sturm leuchten."),
        Species("draconis", 31, "Draconis", listOf(Type.DRACHE, Type.FEUER),
            96, 118, 96, 108, 100, 92, 30, 260, "DRAGON", 0xFF3A2FA8.toInt(), 0xFFFF9040.toInt(),
            ls(1 to "drachenpuls", 50 to "feuersturm", 58 to "drachentanz", 64 to "wutanfall",
                70 to "hyperstrahl"),
            null,
            "Der Koenig der Luefte. Sein Schrei kuendigt Gewitter an."),

        // ---------------------------- Weitere Wildmonster ----------------------------
        Species("glutwurm", 32, "Glutwurm", listOf(Type.FEUER, Type.KAEFER),
            58, 68, 52, 62, 52, 66, 140, 96, "BUG", 0xFFE07030.toInt(), 0xFFFFD860.toInt(),
            ls(1 to "kaeferbiss", 9 to "glut", 16 to "fadenschuss", 24 to "flammenrad",
                32 to "sichelschlag", 40 to "flammenwurf", 48 to "kaefergebrumm"),
            null,
            "Sein Panzer glueht, wenn es sich bedroht fuehlt."),
        Species("korallis", 33, "Korallis", listOf(Type.WASSER, Type.GESTEIN),
            68, 52, 98, 62, 88, 35, 140, 98, "ROCK", 0xFFE87890.toInt(), 0xFF90E0D0.toInt(),
            ls(1 to "aquaknarre", 10 to "haertner", 18 to "steinwurf", 26 to "blubbstrahl",
                34 to "panzerschutz", 42 to "surfer", 50 to "steinkante"),
            null,
            "Ganze Riffe entstehen aus den abgestossenen Aesten dieser Monster."),
        Species("kaktrix", 34, "Kaktrix", listOf(Type.PFLANZE, Type.GESTEIN),
            62, 88, 74, 48, 48, 42, 140, 98, "PLANT", 0xFF4E9C58.toInt(), 0xFFCFC088.toInt(),
            ls(1 to "rankenhieb", 10 to "giftstachel", 18 to "steinwurf", 26 to "kugelsaat",
                34 to "steinhagel", 42 to "blattgeissel", 50 to "erdbeben"),
            null,
            "In der Wueste speichert es Wasser fuer viele Monate."),
        Species("schlammo", 35, "Schlammo", listOf(Type.GIFT, Type.WASSER),
            88, 66, 58, 66, 62, 32, 150, 94, "BLOB", 0xFF6A8C58.toInt(), 0xFFB8D890.toInt(),
            ls(1 to "tackle", 9 to "saeure", 17 to "blubbstrahl", 25 to "matschbombe",
                33 to "surfer", 41 to "toxin", 49 to "schlammbombe"),
            null,
            "Es lebt in truebem Wasser und reinigt es, indem es Abfall frisst."),
        Species("flufflamm", 36, "Flufflamm", listOf(Type.FEUER),
            62, 62, 52, 88, 72, 76, 120, 104, "BLOB", 0xFFF08858.toInt(), 0xFFFFE0B0.toInt(),
            ls(1 to "glut", 12 to "heuler", 20 to "flammenrad", 28 to "hitzeschutz",
                36 to "flammenwurf", 46 to "feuersturm"),
            Evolution("vulkanix", 0, "feuerstein"),
            "Sein flauschiges Fell fuehlt sich an wie warme Asche."),
        Species("vulkanix", 37, "Vulkanix", listOf(Type.FEUER, Type.GESTEIN),
            88, 98, 92, 112, 88, 72, 45, 196, "ROCK", 0xFFC03818.toInt(), 0xFFFFA030.toInt(),
            ls(1 to "flammenwurf", 1 to "steinhagel", 44 to "erdbeben", 52 to "feuersturm",
                60 to "steinkante", 66 to "hyperstrahl"),
            null,
            "In seinem Ruecken brodelt echte Lava. Es schlaeft in Kratern."),
        Species("seeklinge", 38, "Seeklinge", listOf(Type.WASSER),
            56, 72, 56, 58, 56, 86, 130, 100, "FISH", 0xFF3AA0C8.toInt(), 0xFFD8F0FF.toInt(),
            ls(1 to "aquaknarre", 11 to "nassschweif", 19 to "agilitaet", 27 to "aquahaubitze",
                35 to "surfer", 44 to "hydropumpe"),
            Evolution("marino", 0, "wasserstein"),
            "Seine Rueckenflosse ist so scharf, dass sie Treibholz spaltet."),
        Species("marino", 39, "Marino", listOf(Type.WASSER, Type.KAMPF),
            85, 108, 78, 66, 74, 92, 45, 194, "FISH", 0xFF1C74A8.toInt(), 0xFFA8E0F8.toInt(),
            ls(1 to "aquahaubitze", 1 to "karateschlag", 44 to "kreuzhieb", 52 to "hydropumpe",
                60 to "nahkampf", 66 to "hyperstrahl"),
            null,
            "Ein stolzer Kaempfer der Kuesten. Es trainiert gegen die Brandung."),
        Species("knospel", 40, "Knospel", listOf(Type.PFLANZE),
            58, 56, 62, 78, 78, 48, 130, 100, "PLANT", 0xFF66B850.toInt(), 0xFFF0A0C8.toInt(),
            ls(1 to "rankenhieb", 11 to "giftpuder", 19 to "gigasauger", 27 to "wachstum",
                35 to "kugelsaat", 44 to "solarstrahl"),
            Evolution("floranix", 0, "blattstein"),
            "Die Knospe oeffnet sich nur, wenn es genug Sonne getankt hat."),
        Species("floranix", 41, "Floranix", listOf(Type.PFLANZE, Type.KAMPF),
            82, 104, 84, 96, 92, 76, 45, 196, "PLANT", 0xFF2F8E3E.toInt(), 0xFFF87890.toInt(),
            ls(1 to "blattgeissel", 1 to "karateschlag", 44 to "solarstrahl", 52 to "kreuzhieb",
                60 to "nahkampf", 66 to "hyperstrahl"),
            null,
            "Es taenzt zwischen seinen Schlaegen, als waere der Kampf ein Fest."),
        Species("funkling", 42, "Funkling", listOf(Type.ELEKTRO),
            54, 52, 58, 82, 68, 78, 130, 100, "SPARK", 0xFFF8E060.toInt(), 0xFF9098A8.toInt(),
            ls(1 to "donnerschock", 11 to "donnerwelle", 19 to "funkenflug", 27 to "agilitaet",
                35 to "donnerblitz", 44 to "donner"),
            Evolution("gigavolt", 0, "donnerstein"),
            "Es sammelt sich bei Gewitter auf Huegeln und tanzt im Blitzlicht."),
        Species("gigavolt", 43, "Gigavolt", listOf(Type.ELEKTRO, Type.GESTEIN),
            86, 92, 100, 110, 88, 84, 45, 198, "ROCK", 0xFFE8C020.toInt(), 0xFF6A6A7A.toInt(),
            ls(1 to "donnerblitz", 1 to "steinhagel", 44 to "erdbeben", 52 to "donner",
                60 to "steinkante", 66 to "hyperstrahl"),
            null,
            "Es zieht Blitze an und speichert sie in seinem Kristallkern."),

        // ---------------------------- Legendaere Monster ----------------------------
        Species("umbrax", 44, "Umbrax", listOf(Type.GEIST, Type.GIFT),
            88, 92, 88, 118, 96, 100, 12, 250, "GHOST", 0xFF2E2440.toInt(), 0xFF9C40D8.toInt(),
            ls(1 to "spukball", 1 to "toxin", 45 to "konfustrahl", 52 to "schattenklaue",
                58 to "schlammbombe", 64 to "hyperstrahl"),
            null,
            "Ein Schatten aus einer anderen Welt. Der Schattenorden betet es an."),
        Species("titanox", 45, "Titanox", listOf(Type.DRACHE, Type.GESTEIN),
            106, 116, 104, 112, 100, 88, 6, 300, "DRAGON", 0xFF6A5030.toInt(), 0xFF9C58E8.toInt(),
            ls(1 to "drachenpuls", 1 to "erdbeben", 50 to "steinkante", 58 to "drachentanz",
                64 to "wutanfall", 70 to "hyperstrahl"),
            null,
            "Der schlafende Riese unter dem Gipfel. Erwacht er, formen sich Gebirge neu.")
    )

    private val byId = species.associateBy { it.id }

    fun get(id: String): Species = byId[id] ?: species[0]
    fun all(): List<Species> = species
    fun byDexNo(no: Int): Species? = species.firstOrNull { it.dexNo == no }
    fun count(): Int = species.size
}
